export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN'
export const ADD_SHOP_ITEM_IN_CART = 'ADD_SHOP_ITEM_IN_CART'
export const REMOVE_SHOP_ITEM_IN_CART = 'REMOVE_SHOP_ITEM_IN_CART'
export const CLEAR_CART = 'CLEAR_CART'
